# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Arco',
                'verbose_name_plural': 'Arcos',
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('L', 'Localidad'), ('F', 'Estación ferrocarril'), ('A', 'Aeropuerto'), ('S', 'Silos'), ('P', 'Puerto')], max_length=1)),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
            },
        ),
        migrations.AddField(
            model_name='arco',
            name='nodo_desde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_desde', to='core.Nodo'),
        ),
        migrations.AddField(
            model_name='arco',
            name='nodo_hasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_hasta', to='core.Nodo'),
        ),
    ]
